spring.application.name=app
server.port=${PORT:8081}

spring.datasource.hikari.data-source-properties.sslmode=require
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=false

gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=${GEMINI_API_URL}